### ISSUE TITLE
add bounds to the drag?

### ISSUE THREAD

**Issue by Seb-AS** [transcriptic/react-map-interaction#13] opened 2018-06-16 22:36 UTC

**Comment by scottyantipa** [comment] 2018-06-18 16:29
Thanks for the issue, but marking this  duplicate of: #8 
Let me now if there is a difference between the two.

If you have the time @Seb-AS we'd love to see a screen shot or description of how you're using map-interaction in your project!

**Closed** 2018-07-03 18:58 UTC
Labels: duplicate
